name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code into /var/www/html
        uses: actions/checkout@v4
        with:
          path: /var/www/html

      - name: Laravel deployment
        run: |
          cd /var/www/html
          composer install --no-interaction --prefer-dist --optimize-autoloader
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
