name: Deploy Laravel App to /var/www/html

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo (into default workspace)
        uses: actions/checkout@v4

      - name: Deploy to /var/www/html
        run: |
          sudo rsync -a --delete $GITHUB_WORKSPACE/ /var/www/html/

      - name: Laravel deploy steps
        run: |
          cd /var/www/html
          composer install --no-interaction --prefer-dist --optimize-autoloader
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
